### ISSUE TITLE
How can I get all English vocabularies in Hatebase?

### ISSUE THREAD

**Issue by isabelline** [DanielJDufour/hatebase#2]
```
from hatebase import HatebaseAPI
key = '~'
hatebase = HatebaseAPI({"key": key})
hatebase = HatebaseAPI({"key": key, "debug": True})
filters = {"language": "eng"}
format = "json"

response = hatebase.getVocabulary(filters=filters, format=format)

vocablist = response["result"]
results = response["number_of_results"]
pages = response["number_of_pages"]
```

If I run the code above, I get vocablist with length 100, results with length 1522, and pages as length 16.
I thought I would get the whole vocabulary of English HateBase words by this query but there were only 100 vocabularies returned.
Is there any way I could get the whole vocabulary?
Thanks.

**Comment by DanielJDufour** [comment]
Hi, @isabelline .  Thank you for your question.  @meierale, could you help?

**Comment by meierale** [comment]
Hi @isabelline. Please try to adapt the Ara example to english: https://github.com/DanielJDufour/hatebase#get-all-arabic-vocabulary 

The hatebase API limits its resultsets to max 100 vocabulary entries, but indicates how many total results on how many pages there are. So your code above contains the 100 vocab entries of the first page. Now you have to query all remaining pages, get their 100 entries and append them all to the 'full vocabulary' that you have to build yourself. The 'Get All Arabic Vocabulary' example in the readme shows how I usually do that. 
Try to copy & paste that code, switch the language filter to "eng" and it should work right away. And for the English vocabulary it will take some time to loop through all pages, just so you know ;-)

Please let me know if that works for you.

**Comment by isabelline** [comment]
@meierale @DanielJDufour  Thank you! It works like a charm :)
